export { default as icArrow } from './ic_arrow.svg'
export { default as icClose } from './ic_close.svg'
export { default as icGithub } from './ic_github.svg'
export { default as icHamburger } from './ic_hamburger.svg'
export { default as icLogo } from './ic_logo.svg'
