export { default as IconArrow } from './ic_arrow.svg'
export { default as IconClose } from './ic_close.svg'
export { default as IconGithub } from './ic_github.svg'
export { default as IconHamburger } from './ic_hamburger.svg'
export { default as IconLogo } from './ic_logo.svg'
export { default as IconBestseller } from './ic_bestseller.svg'
